linters:
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - containedctx
  - contextcheck
  - decorder
  - dogsled
  - dupl
  - dupword
  - durationcheck
  - errcheck
  - errchkjson
  - errorlint
  - execinquery
  - exportloopref
  - forbidigo
  - forcetypeassert
  - gci
  - ginkgolinter
  - gocheckcompilerdirectives
  - gochecknoinits
  - gochecksumtype
  - gocritic
  - godot
  - goerr113
  - gofmt
  - gofumpt
  - goimports
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - gosmopolitan
  - govet
  - grouper
  - importas
  - inamedparam
  - ineffassign
  - interfacebloat
  - ireturn
  - loggercheck
  - makezero
  - mirror
  - misspell
  - musttag
  - nakedret
  - nilerr
  - nilnil
  - noctx
  - nolintlint
  - nosprintfhostport
  - perfsprint
  - prealloc
  - predeclared
  - promlinter
  - protogetter
  - reassign
  - revive
  - rowserrcheck
  - sloglint
  - spancheck
  - sqlclosecheck
  - staticcheck
  - stylecheck
  - tagalign
  - tagliatelle
  - tenv
  - testableexamples
  - testifylint
  - thelper
  - tparallel
  - typecheck
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - whitespace
  - zerologlint
  disable:
  - cyclop
  - depguard
  - errname # FIXME renaming ErrXxx to XxxError will require a major version bump
  - exhaustive
  - exhaustruct
  - funlen
  - gochecknoglobals
  - gocognit
  - goconst
  - gocyclo
  - godox
  - goheader
  - gomnd
  - lll
  - maintidx
  - nestif
  - nlreturn
  - nonamedreturns
  - paralleltest
  - paralleltest
  - testpackage
  - testpackage
  - varnamelen
  - wastedassign # https://github.com/golangci/golangci-lint/issues/2649
  - wrapcheck
  - wsl

linters-settings:
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/twpayne/go-geom)
  goimports:
    local-prefixes: github.com/twpayne/go-geom
  ireturn:
    allow:
    - error
    - stdlib
    - ^github\.com/twpayne/go-geom\.T$
    - ^github\.com/twpayne/go-kml/v3\.Element$

issues:
  exclude-rules:
  - linters:
    - dupl
    - scopelint
    path: "_test\\.go"
  - linters:
    - godot
    path: "^bigxy/"
  - linters:
    - gocritic
    path: "_example_test\\.go$"
  - linters:
    - godot
    path: "^sorting/"
  - linters:
    - godot
    path: "^transform/"
  - linters:
    - gocritic
    - godot
    path: "^xy/"
  - linters:
    - godot
    path: "^xyz/"
  - linters:
    - goerr113
    text: "do not define dynamic errors, use wrapped static errors instead"
  - linters:
    - forbidigo
    path: "^internal/cmd/"